"""The asset stages and their versions.

Bump a stage's number when its output changes shape or content in a way
the game must have (a new field, a fixed exporter, another dungeon). The
builder writes what it built into assets/build_manifest.json; the game
ships this same table (game/scripts/asset_versions.gd, generated by
build_dist.py) and, when the two disagree, runs setup.exe to redo just
the stages that moved before it starts. Everything else (a caught bug in
a dungeon's placement, a texture fallback) rides on the WMO and creature
caches inside the dungeon stage and needs no bump here.
"""

STAGES = {
    "d2:tables": 1,        # gamedata.json: skills, skilldesc, missiles, monsters
    "d2:ui": 2,            # interface art, fonts' sheets (2: vendor + stash screens)
    "d2:missiles": 1,      # missile sprites
    "d2:amazon": 1,        # the Amazon's animation sheets
    "d2:paperdoll": 1,     # menu paperdoll layers
    "d2:layers": 1,        # gear layers for the co-op puppets
    "d2:monsters": 1,      # summon sprites
    "d2:items": 2,         # item catalog + art (2: dropsound columns)
    "d2:affixes": 1,       # uniques, sets, affixes
    "d2:statdisplay": 1,   # stat text + fonts
    "d2:sounds": 2,        # sound effects (2: the item drop sounds)
    "d2:setbonus": 1,      # set bonuses
    "wow:dungeons": 2,     # every dungeon (2: liquid grids, texture fallbacks)
    "wow:outpost": 1,      # the vendor and the stash chest by every entrance
    "wow:backdrops": 1,    # menu backdrops
    "wow:soundscape": 1,   # ambience and music
}

# the D2 stages in the order the builder runs them; the WoW three follow
ORDER = ["d2:tables", "d2:ui", "d2:missiles", "d2:amazon", "d2:paperdoll",
         "d2:layers", "d2:monsters", "d2:items", "d2:affixes", "d2:statdisplay",
         "d2:sounds", "d2:setbonus", "wow:dungeons", "wow:outpost",
         "wow:backdrops", "wow:soundscape"]


def stale(manifest):
    """The stages a manifest (the dict from build_manifest.json, or None)
    lacks or has at an older version, in build order."""
    built = (manifest or {}).get("stages", {}) if isinstance(manifest, dict) else {}
    return [k for k in ORDER if int(built.get(k, 0)) != STAGES[k]]
