class_name AssetVersions
## Generated by pipeline/build_dist.py from pipeline/versions.py: the asset
## stages this build of the game expects, by version. The updater compares
## them with _build/assets/build_manifest.json and has setup.exe redo the
## stages that moved. Edit versions.py, not this file.

const STAGES := {
	"d2:tables": 1,
	"d2:ui": 2,
	"d2:missiles": 1,
	"d2:amazon": 1,
	"d2:paperdoll": 1,
	"d2:layers": 1,
	"d2:monsters": 1,
	"d2:items": 2,
	"d2:affixes": 1,
	"d2:statdisplay": 1,
	"d2:sounds": 2,
	"d2:setbonus": 1,
	"wow:dungeons": 2,
	"wow:outpost": 1,
	"wow:backdrops": 1,
	"wow:soundscape": 1,
}
